package promi.meldeamtPackage;


/**
* promi/meldeamtPackage/Emotion.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./src/main/java/my_modul.idl
* Dienstag, 26. April 2022 16:32 Uhr MESZ
*/

public class Emotion implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 2;
  private static promi.meldeamtPackage.Emotion[] __array = new promi.meldeamtPackage.Emotion [__size];

  public static final int _Positiv = 0;
  public static final promi.meldeamtPackage.Emotion Positiv = new promi.meldeamtPackage.Emotion(_Positiv);
  public static final int _Negativ = 1;
  public static final promi.meldeamtPackage.Emotion Negativ = new promi.meldeamtPackage.Emotion(_Negativ);

  public int value ()
  {
    return __value;
  }

  public static promi.meldeamtPackage.Emotion from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected Emotion (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class Emotion
