package promi.meldeamtPackage;

/**
* promi/meldeamtPackage/EmotionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./src/main/java/my_modul.idl
* Dienstag, 26. April 2022 16:32 Uhr MESZ
*/

public final class EmotionHolder implements org.omg.CORBA.portable.Streamable
{
  public promi.meldeamtPackage.Emotion value = null;

  public EmotionHolder ()
  {
  }

  public EmotionHolder (promi.meldeamtPackage.Emotion initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = promi.meldeamtPackage.EmotionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    promi.meldeamtPackage.EmotionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return promi.meldeamtPackage.EmotionHelper.type ();
  }

}
