package promi.meldeamtPackage;


/**
* promi/meldeamtPackage/Key.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./src/main/java/my_modul.idl
* Dienstag, 26. April 2022 16:32 Uhr MESZ
*/

public class Key implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 2;
  private static promi.meldeamtPackage.Key[] __array = new promi.meldeamtPackage.Key [__size];

  public static final int _P = 0;
  public static final promi.meldeamtPackage.Key P = new promi.meldeamtPackage.Key(_P);
  public static final int _N = 1;
  public static final promi.meldeamtPackage.Key N = new promi.meldeamtPackage.Key(_N);

  public int value ()
  {
    return __value;
  }

  public static promi.meldeamtPackage.Key from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected Key (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class Key
