package promi.meldeamtPackage;


/**
* promi/meldeamtPackage/KeyHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./src/main/java/my_modul.idl
* Dienstag, 26. April 2022 16:32 Uhr MESZ
*/

abstract public class KeyHelper
{
  private static String  _id = "IDL:promi/meldeamt/Key:1.0";

  public static void insert (org.omg.CORBA.Any a, promi.meldeamtPackage.Key that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static promi.meldeamtPackage.Key extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_enum_tc (promi.meldeamtPackage.KeyHelper.id (), "Key", new String[] { "P", "N"} );
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static promi.meldeamtPackage.Key read (org.omg.CORBA.portable.InputStream istream)
  {
    return promi.meldeamtPackage.Key.from_int (istream.read_long ());
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, promi.meldeamtPackage.Key value)
  {
    ostream.write_long (value.value ());
  }

}
