package promi.meldeamtPackage;

/**
* promi/meldeamtPackage/KeyHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./src/main/java/my_modul.idl
* Dienstag, 26. April 2022 16:32 Uhr MESZ
*/

public final class KeyHolder implements org.omg.CORBA.portable.Streamable
{
  public promi.meldeamtPackage.Key value = null;

  public KeyHolder ()
  {
  }

  public KeyHolder (promi.meldeamtPackage.Key initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = promi.meldeamtPackage.KeyHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    promi.meldeamtPackage.KeyHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return promi.meldeamtPackage.KeyHelper.type ();
  }

}
