package promi.meldeamtPackage;


/**
* promi/meldeamtPackage/U.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./src/main/java/my_modul.idl
* Dienstag, 26. April 2022 16:32 Uhr MESZ
*/

public final class U implements org.omg.CORBA.portable.IDLEntity
{
  private promi.Pass ___pass;
  private promi.Name ___name;
  private promi.meldeamtPackage.Key __discriminator;
  private boolean __uninitialized = true;

  public U ()
  {
  }

  public promi.meldeamtPackage.Key discriminator ()
  {
    if (__uninitialized)
      throw new org.omg.CORBA.BAD_OPERATION ();
    return __discriminator;
  }

  public promi.Pass pass ()
  {
    if (__uninitialized)
      throw new org.omg.CORBA.BAD_OPERATION ();
    verifypass (__discriminator);
    return ___pass;
  }

  public void pass (promi.Pass value)
  {
    __discriminator = promi.meldeamtPackage.Key.P;
    ___pass = value;
    __uninitialized = false;
  }

  public void pass (promi.meldeamtPackage.Key discriminator, promi.Pass value)
  {
    verifypass (discriminator);
    __discriminator = discriminator;
    ___pass = value;
    __uninitialized = false;
  }

  private void verifypass (promi.meldeamtPackage.Key discriminator)
  {
    if (discriminator != promi.meldeamtPackage.Key.P)
      throw new org.omg.CORBA.BAD_OPERATION ();
  }

  public promi.Name name ()
  {
    if (__uninitialized)
      throw new org.omg.CORBA.BAD_OPERATION ();
    verifyname (__discriminator);
    return ___name;
  }

  public void name (promi.Name value)
  {
    __discriminator = promi.meldeamtPackage.Key.N;
    ___name = value;
    __uninitialized = false;
  }

  public void name (promi.meldeamtPackage.Key discriminator, promi.Name value)
  {
    verifyname (discriminator);
    __discriminator = discriminator;
    ___name = value;
    __uninitialized = false;
  }

  private void verifyname (promi.meldeamtPackage.Key discriminator)
  {
    if (discriminator != promi.meldeamtPackage.Key.N)
      throw new org.omg.CORBA.BAD_OPERATION ();
  }

} // class U
