package promi.meldeamtPackage;


/**
* promi/meldeamtPackage/UHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./src/main/java/my_modul.idl
* Dienstag, 26. April 2022 16:32 Uhr MESZ
*/

abstract public class UHelper
{
  private static String  _id = "IDL:promi/meldeamt/U:1.0";

  public static void insert (org.omg.CORBA.Any a, promi.meldeamtPackage.U that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static promi.meldeamtPackage.U extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      org.omg.CORBA.TypeCode _disTypeCode0;
      _disTypeCode0 = promi.meldeamtPackage.KeyHelper.type ();
      org.omg.CORBA.UnionMember[] _members0 = new org.omg.CORBA.UnionMember [2];
      org.omg.CORBA.TypeCode _tcOf_members0;
      org.omg.CORBA.Any _anyOf_members0;

      // Branch for pass (case label P)
      _anyOf_members0 = org.omg.CORBA.ORB.init ().create_any ();
      promi.meldeamtPackage.KeyHelper.insert (_anyOf_members0, promi.meldeamtPackage.Key.P);
      _tcOf_members0 = promi.PassHelper.type ();
      _members0[0] = new org.omg.CORBA.UnionMember (
        "pass",
        _anyOf_members0,
        _tcOf_members0,
        null);

      // Branch for name (case label N)
      _anyOf_members0 = org.omg.CORBA.ORB.init ().create_any ();
      promi.meldeamtPackage.KeyHelper.insert (_anyOf_members0, promi.meldeamtPackage.Key.N);
      _tcOf_members0 = promi.NameHelper.type ();
      _members0[1] = new org.omg.CORBA.UnionMember (
        "name",
        _anyOf_members0,
        _tcOf_members0,
        null);
      __typeCode = org.omg.CORBA.ORB.init ().create_union_tc (promi.meldeamtPackage.UHelper.id (), "U", _disTypeCode0, _members0);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static promi.meldeamtPackage.U read (org.omg.CORBA.portable.InputStream istream)
  {
    promi.meldeamtPackage.U value = new promi.meldeamtPackage.U ();
    promi.meldeamtPackage.Key _dis0 = null;
    _dis0 = promi.meldeamtPackage.KeyHelper.read (istream);
    switch (_dis0.value ())
    {
      case promi.meldeamtPackage.Key._P:
        promi.Pass _pass = null;
        _pass = promi.PassHelper.read (istream);
        value.pass (_pass);
        break;
      case promi.meldeamtPackage.Key._N:
        promi.Name _name = null;
        _name = promi.NameHelper.read (istream);
        value.name (_name);
        break;
    }
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, promi.meldeamtPackage.U value)
  {
    promi.meldeamtPackage.KeyHelper.write (ostream, value.discriminator ());
    switch (value.discriminator ().value ())
    {
      case promi.meldeamtPackage.Key._P:
        promi.PassHelper.write (ostream, value.pass ());
        break;
      case promi.meldeamtPackage.Key._N:
        promi.NameHelper.write (ostream, value.name ());
        break;
    }
  }

}
