package promi.meldeamtPackage;

/**
* promi/meldeamtPackage/UHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./src/main/java/my_modul.idl
* Dienstag, 26. April 2022 16:32 Uhr MESZ
*/

public final class UHolder implements org.omg.CORBA.portable.Streamable
{
  public promi.meldeamtPackage.U value = null;

  public UHolder ()
  {
  }

  public UHolder (promi.meldeamtPackage.U initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = promi.meldeamtPackage.UHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    promi.meldeamtPackage.UHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return promi.meldeamtPackage.UHelper.type ();
  }

}
