
/**
* nameHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./src/main/java/my_modul.idl
* Dienstag, 26. April 2022 15:22 Uhr MESZ
*/

public final class nameHolder implements org.omg.CORBA.portable.Streamable
{
  public name value = null;

  public nameHolder ()
  {
  }

  public nameHolder (name initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = nameHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    nameHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return nameHelper.type ();
  }

}
