
/**
* name.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./src/main/java/my_modul.idl
* Dienstag, 26. April 2022 15:22 Uhr MESZ
*/

public final class name implements org.omg.CORBA.portable.IDLEntity
{
  public String nachname = null;
  public String vorname[] = null;

  public name ()
  {
  } // ctor

  public name (String _nachname, String[] _vorname)
  {
    nachname = _nachname;
    vorname = _vorname;
  } // ctor

} // class name
