package promi.promiPackage;

/**
* promi/promiPackage/AbsageHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./src/main/java/my_modul.idl
* Dienstag, 26. April 2022 16:32 Uhr MESZ
*/

public final class AbsageHolder implements org.omg.CORBA.portable.Streamable
{
  public promi.promiPackage.Absage value = null;

  public AbsageHolder ()
  {
  }

  public AbsageHolder (promi.promiPackage.Absage initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = promi.promiPackage.AbsageHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    promi.promiPackage.AbsageHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return promi.promiPackage.AbsageHelper.type ();
  }

}
