package promi.promiPackage;


/**
* promi/promiPackage/Absage.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./src/main/java/my_modul.idl
* Dienstag, 26. April 2022 16:32 Uhr MESZ
*/

public final class Absage extends org.omg.CORBA.UserException
{
  public int error_code = (int)0;
  public promi.promiPackage.Reasons raisons = null;

  public Absage ()
  {
    super(AbsageHelper.id());
  } // ctor

  public Absage (int _error_code, promi.promiPackage.Reasons _raisons)
  {
    super(AbsageHelper.id());
    error_code = _error_code;
    raisons = _raisons;
  } // ctor


  public Absage (String $reason, int _error_code, promi.promiPackage.Reasons _raisons)
  {
    super(AbsageHelper.id() + "  " + $reason);
    error_code = _error_code;
    raisons = _raisons;
  } // ctor

} // class Absage
