package promi.promiPackage;


/**
* promi/promiPackage/AbsageHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./src/main/java/my_modul.idl
* Dienstag, 26. April 2022 16:32 Uhr MESZ
*/

abstract public class AbsageHelper
{
  private static String  _id = "IDL:promi/promi/Absage:1.0";

  public static void insert (org.omg.CORBA.Any a, promi.promiPackage.Absage that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static promi.promiPackage.Absage extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [2];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[0] = new org.omg.CORBA.StructMember (
            "error_code",
            _tcOf_members0,
            null);
          _tcOf_members0 = promi.promiPackage.ReasonsHelper.type ();
          _members0[1] = new org.omg.CORBA.StructMember (
            "raisons",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_exception_tc (promi.promiPackage.AbsageHelper.id (), "Absage", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static promi.promiPackage.Absage read (org.omg.CORBA.portable.InputStream istream)
  {
    promi.promiPackage.Absage value = new promi.promiPackage.Absage ();
    // read and discard the repository ID
    istream.read_string ();
    value.error_code = istream.read_long ();
    value.raisons = promi.promiPackage.ReasonsHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, promi.promiPackage.Absage value)
  {
    // write the repository ID
    ostream.write_string (id ());
    ostream.write_long (value.error_code);
    promi.promiPackage.ReasonsHelper.write (ostream, value.raisons);
  }

}
