package promi.promiPackage;

/**
* promi/promiPackage/RaisonsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./src/main/java/my_modul.idl
* Dienstag, 26. April 2022 16:24 Uhr MESZ
*/

public final class RaisonsHolder implements org.omg.CORBA.portable.Streamable
{
  public promi.promiPackage.Raisons value = null;

  public RaisonsHolder ()
  {
  }

  public RaisonsHolder (promi.promiPackage.Raisons initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = promi.promiPackage.RaisonsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    promi.promiPackage.RaisonsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return promi.promiPackage.RaisonsHelper.type ();
  }

}
