package promi.promiPackage;

/**
* promi/promiPackage/ReasonsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./src/main/java/my_modul.idl
* Dienstag, 26. April 2022 16:32 Uhr MESZ
*/

public final class ReasonsHolder implements org.omg.CORBA.portable.Streamable
{
  public promi.promiPackage.Reasons value = null;

  public ReasonsHolder ()
  {
  }

  public ReasonsHolder (promi.promiPackage.Reasons initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = promi.promiPackage.ReasonsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    promi.promiPackage.ReasonsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return promi.promiPackage.ReasonsHelper.type ();
  }

}
