package promi.promiPackage;


/**
* promi/promiPackage/Reasons.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./src/main/java/my_modul.idl
* Dienstag, 26. April 2022 16:32 Uhr MESZ
*/

public class Reasons implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 3;
  private static promi.promiPackage.Reasons[] __array = new promi.promiPackage.Reasons [__size];

  public static final int _EINS = 0;
  public static final promi.promiPackage.Reasons EINS = new promi.promiPackage.Reasons(_EINS);
  public static final int _ZWEI = 1;
  public static final promi.promiPackage.Reasons ZWEI = new promi.promiPackage.Reasons(_ZWEI);
  public static final int _DREI = 2;
  public static final promi.promiPackage.Reasons DREI = new promi.promiPackage.Reasons(_DREI);

  public int value ()
  {
    return __value;
  }

  public static promi.promiPackage.Reasons from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected Reasons (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class Reasons
