package promi.promiPackage;

/**
* promi/promiPackage/WohnortHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./src/main/java/my_modul.idl
* Dienstag, 26. April 2022 16:32 Uhr MESZ
*/

public final class WohnortHolder implements org.omg.CORBA.portable.Streamable
{
  public promi.promiPackage.Wohnort value = null;

  public WohnortHolder ()
  {
  }

  public WohnortHolder (promi.promiPackage.Wohnort initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = promi.promiPackage.WohnortHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    promi.promiPackage.WohnortHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return promi.promiPackage.WohnortHelper.type ();
  }

}
