package promi;

/**
* promi/meldeamtHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./src/main/java/my_modul.idl
* Dienstag, 26. April 2022 16:32 Uhr MESZ
*/

public final class meldeamtHolder implements org.omg.CORBA.portable.Streamable
{
  public promi.meldeamt value = null;

  public meldeamtHolder ()
  {
  }

  public meldeamtHolder (promi.meldeamt initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = promi.meldeamtHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    promi.meldeamtHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return promi.meldeamtHelper.type ();
  }

}
