package promi;


/**
* promi/meldeamt.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./src/main/java/my_modul.idl
* Dienstag, 26. April 2022 16:32 Uhr MESZ
*/

public interface meldeamt extends meldeamtOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface meldeamt
