package promi;


/**
* promi/menschHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./src/main/java/my_modul.idl
* Dienstag, 26. April 2022 16:32 Uhr MESZ
*/

abstract public class menschHelper
{
  private static String  _id = "IDL:promi/mensch:1.0";

  public static void insert (org.omg.CORBA.Any a, promi.mensch that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static promi.mensch extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (promi.menschHelper.id (), "mensch");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static promi.mensch read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_menschStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, promi.mensch value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static promi.mensch narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof promi.mensch)
      return (promi.mensch)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      promi._menschStub stub = new promi._menschStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static promi.mensch unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof promi.mensch)
      return (promi.mensch)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      promi._menschStub stub = new promi._menschStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
