package promi;


/**
* promi/menschOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./src/main/java/my_modul.idl
* Dienstag, 26. April 2022 16:32 Uhr MESZ
*/

public interface menschOperations 
{
  promi.Name name ();
  promi.Pass reisepass ();
  void reisepass (promi.Pass newReisepass);
} // interface menschOperations
