package promi;


/**
* promi/Name.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./src/main/java/my_modul.idl
* Dienstag, 26. April 2022 16:32 Uhr MESZ
*/

public final class Name implements org.omg.CORBA.portable.IDLEntity
{
  public String nachname = null;
  public String vornamen[] = null;

  public Name ()
  {
  } // ctor

  public Name (String _nachname, String[] _vornamen)
  {
    nachname = _nachname;
    vornamen = _vornamen;
  } // ctor

} // class Name
