package promi;


/**
* promi/promiOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./src/main/java/my_modul.idl
* Dienstag, 26. April 2022 16:32 Uhr MESZ
*/

public interface promiOperations  extends promi.menschOperations
{
  promi.promiPackage.Wohnort[] wohnorte ();
  void wohnorte (promi.promiPackage.Wohnort[] newWohnorte);
  void zuziehen (promi.promiPackage.Wohnort wohnorte) throws promi.promiPackage.Absage;
  String interview1 (promi.reporter reporter);
  void interview2 (promi.reporter reporter, org.omg.CORBA.StringHolder dok);
} // interface promiOperations
