package promi;

/**
* promi/promiHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./src/main/java/my_modul.idl
* Dienstag, 26. April 2022 16:32 Uhr MESZ
*/

public final class promiHolder implements org.omg.CORBA.portable.Streamable
{
  public promi.promi value = null;

  public promiHolder ()
  {
  }

  public promiHolder (promi.promi initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = promi.promiHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    promi.promiHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return promi.promiHelper.type ();
  }

}
